export const ADD_GENERIC_FILTER_PANEL = 'ADD_GENERIC_FILTER_PANEL';
export const ADD_GENERIC_LIST_PANEL = 'ADD_GENERIC_LIST_PANEL';
export const ADD_GENERIC_SUMMARY_PANEL = 'ADD_GENERIC_SUMMARY_PANEL';
export const UPDATE_GRID_LAYOUT = 'UPDATE_GRID_LAYOUT';
